<script type="text/javascript" src="/assets/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-ui-1.9.2.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/assets/js/newBiz.js"></script>
<link href="/assets/css/newBiz.css" media="screen" rel="stylesheet" type="text/css" />
<section id="addbiz">
	<div id="addbizform">
		<?php echo $this->form; ?>
	</div>
	<div id="mapCanvas"></div>
	<a id="showoptional" href="#">Campos opcionales</a>
</section>