<script type="text/javascript" src="/assets/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-ui-1.9.2.min.js"></script>
<script type="text/javascript" src="/assets/js/newUser.js"></script>
<link href="/assets/css/newUser.css" media="screen" rel="stylesheet" type="text/css" />
<section id="adduser">
<a id="showoptional" href="#">Campos opcionales</a>
	<div id="adduserform">
		<?php echo $this->form; ?>
	</div>
</section>